[2018-04-20 10:27:43] ERROR [<module>: worker.py, 141] erroe
